<a href="https://colab.research.google.com/github/jihopark-blue/studyingisfun/blob/main/%ED%86%B5%EA%B3%84%ED%95%99%EA%B0%9C%EB%A1%A01%EA%B0%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 객체의 생성과 저장

객체 이름 <- 저장하고 싶은 값

In [1]:
a <- 1
b <- 1
c <- a+b
c

[1] 2

## 벡터(vector)

- 벡터: 어떤 요소(값)들이 일렬로 늘어선 것
- 벡터를 만드는 법
    - c() 함수 안에 벡터의 각 요소를 쉼표로 구분하여 넣는다.
    - seq() 등의 함수를 이용한다.

In [24]:
height <- c(165, 151, 162, 160, 151, 152, 159, 163, 143, 161)
height

[1] 165 151 162 160 151 152 159 163 143 161

In [25]:
d <- 1:3
d

[1] 1 2 3

In [26]:
e <- seq(1, 9, 2)
e

[1] 1 3 5 7 9

In [28]:
f <- rep(10, 5)
f

[1] 10 10 10 10 10

In [29]:
g <- c(d, f)
g

[1]  1  2  3 10 10 10 10 10

In [30]:
h <- c(4:1, seq(0, 9, 3))
h

[1] 4 3 2 1 0 3 6 9

## 벡터의 연산

- 벡터들 간 사칙연산 가능
    - 벡터의 길이가 같은 경우: 각 벡터에서 같은 위치에 있는 숫자끼리 연산
    - 벡터의 길이가 다른 경우: 길이가 짧은 벡터의 각 요소를 앞에서부터 재활용하면서 연산 (경고 메시지 출력)

In [23]:
e+f

[1] 11 13 15 17 19

In [5]:
e-f

[1] -9 -7 -5 -3 -1

In [6]:
e*f

[1] 10 30 50 70 90

In [7]:
e/f

[1] 0.1 0.3 0.5 0.7 0.9

In [8]:
d+f

Warning message in d + f:
“longer object length is not a multiple of shorter object length”


[1] 11 12 13 11 12

## 데이터형

- 숫자형: 사칙연산 가능
- 범주형: factor() 또는 as.factor() 이용하여 생성
- 문자형: as.character() 이용하여 생성
- 논리형: TRUE 또는 FALSE 값을 가진다.

In [9]:
i <- 1:4
j <- as.factor(1:4)

In [10]:
i+1

[1] 2 3 4 5

In [11]:
j+1

Warning message in Ops.factor(j, 1):
“‘+’ not meaningful for factors”


[1] NA NA NA NA

In [32]:
k <- as.character(1:4)
k

[1] "1" "2" "3" "4"

In [33]:
l <- c("K", "N", "O", "U")
l

[1] "K" "N" "O" "U"

In [34]:
m <- i>2
m

[1] FALSE FALSE  TRUE  TRUE

## 행렬(matrix)

- 벡터 여러개의 모임
- 행렬의 요소들은 데이터형이 모두 같아야 한다
- cbind(), rbind(), matrix() 함수 이용해서 생성

In [35]:
n <- rep(10, 5)
n

[1] 10 10 10 10 10

In [36]:
o <- 1:5
o

[1] 1 2 3 4 5

In [37]:
p <- cbind(n, o)
p

n  o
[1,] 10 1
[2,] 10 2
[3,] 10 3
[4,] 10 4
[5,] 10 5

In [39]:
q <- rbind(n, o)
q

[,1] [,2] [,3] [,4] [,5]
n 10   10   10   10   10  
o  1    2    3    4    5

In [40]:
r <- matrix(1:4, 2, 2)
r

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [41]:
s <- matrix(c(1, 4, 2, 7), 2, 2)
s

[,1] [,2]
[1,] 1    2   
[2,] 4    7

In [42]:
r+s

[,1] [,2]
[1,] 2     5  
[2,] 6    11

In [43]:
r %*% s

[,1] [,2]
[1,] 13   23  
[2,] 18   32

In [44]:
solve(s)

[,1] [,2]
[1,] -7    2  
[2,]  4   -1

In [45]:
s[1, 2]

[1] 2

In [46]:
s[1,]

[1] 1 2

In [47]:
s[,2]

[1] 2 7

## 데이터 프레임 (data frame)

- 행렬과 비슷하나 데이터형이 다른 벡터들도 하나의 데이터 프레임에 저장 가능
- data.frame() 함수 이용해서 생성

In [49]:
name <- c('Kim', 'Lee', 'Park', 'Choi')
age <- c(20, 32, 17, 51)
sex <- as.factor(c('Male', 'Female', 'Female', 'Female'))

dat <- data.frame(name, age, sex)

In [50]:
dat$age

[1] 20 32 17 51

In [51]:
dat$name

[1] "Kim"  "Lee"  "Park" "Choi"

In [52]:
dat$sex

[1] Male   Female Female Female
Levels: Female Male